# example of nested toml structure
[bench]
[bench.transposePerf]
[bench.transposePerf.transposePerf]
[bench.transposePerf.transposePerf.execopts]
m10=["--m=10", "--iters=1000", "--reference=true"]
m1000=["--m=1000", "--iters=10", "--reference=true"]
m10000=["--m=10000", "--iters=1", "--reference=false"]

